// A constructor function is just a normal function
// By convention we capitalise the first character of the name

function Developer(name) {
    // `this` is an empty object that is created implicitly
    this.name = name;

    // When executed, the function implicitly returns `this`
}

// To use a function as a constructor, call it with the `new` keyword

var alice = new Developer('Alice');

console.log('This Developer is called ' + alice.name);

// We can add methods to objects generated by the constructor function
// by extending the constructor's prototype

Developer.prototype.sayHello = function() {
    console.log('Hello, my name is ' + this.name);
};

alice.sayHello();

// We can implement classical inheritance

function JavaScriptDeveloper(name) {
    this.name = name;
}

// Creating the child's prototype based on the parent's prototype

JavaScriptDeveloper.prototype = Object.create(Developer.prototype);

var bob = new JavaScriptDeveloper('Bob');

bob.sayHello();

// But if we mutate the parent's prototype, the change will ripple through to the child

Developer.prototype.sayHello = function() {
    console.log('I am ' + this.name);
};

alice.sayHello();
bob.sayHello();
